return {
    keywords = {
        ["and"] = true, ["break"] = true, ["do"] = true, ["else"] = true, ["elseif"] = true, ["end"] = true,
        ["false"] = true, ["for"] = true, ["function"] = true, ["if"] = true, ["in"] = true, ["local"] = true,
        ["nil"] = true, ["not"] = true, ["or"] = true, ["repeat"] = true, ["return"] = true, ["then"] = true,
        ["true"] = true, ["until"] = true, ["while"] = true,
        ["task"] = true, ["task.spawn"] = true, ["task.defer"] = true, ["task.delay"] = true, ["task.wait"] = true,
        ["task.cancel"] = true, ["task.synchronize"] = true, ["task.desynchronize"] = true,
        ["coroutine"] = true, ["coroutine.wrap"] = true, ["coroutine.create"] = true, ["coroutine.resume"] = true,
        ["coroutine.yield"] = true,
        ["getgenv"] = true, ["getrenv"] = true, ["getgc"] = true, ["getreg"] = true,
        ["getupvalue"] = true, ["setupvalue"] = true, ["hookfunction"] = true, ["hookmetamethod"] = true,
        ["getrawmetatable"] = true, ["setreadonly"] = true, ["newcclosure"] = true,
        ["iscclosure"] = true, ["islclosure"] = true, ["loadstring"] = true,
        ["writefile"] = true, ["readfile"] = true, ["appendfile"] = true, ["isfile"] = true,
        ["delfile"] = true, ["makefolder"] = true, ["delfolder"] = true, ["listfiles"] = true,
        ["request"] = true, ["http_request"] = true, ["syn"] = true, ["syn.request"] = true,
        ["protect_gui"] = true, ["unprotect_gui"] = true, ["gethui"] = true,
        ["queue_on_teleport"] = true, ["firesignal"] = true, ["firetouchinterest"] = true,
        ["fireproximityprompt"] = true, ["getconnections"] = true, ["getloadedmodules"] = true,
        ["getnilinstances"] = true, ["cloneref"] = true, ["compareinstances"] = true,
    },
    builtins = {
        ["print"] = true, ["warn"] = true, ["error"] = true, ["tostring"] = true, ["tonumber"] = true,
        ["type"] = true, ["typeof"] = true, ["pairs"] = true, ["ipairs"] = true, ["next"] = true,
        ["setmetatable"] = true, ["getmetatable"] = true, ["rawequal"] = true, ["rawget"] = true,
        ["rawset"] = true, ["collectgarbage"] = true,
        ["game"] = true, ["workspace"] = true, ["script"] = true, ["shared"] = true, ["_G"] = true,
        ["math"] = true, ["string"] = true, ["table"] = true, ["os"] = true, ["tick"] = true,
        ["time"] = true, ["DateTime"] = true, ["Enum"] = true,
        ["Vector3"] = true, ["Vector2"] = true, ["CFrame"] = true, ["UDim2"] = true, ["Color3"] = true,
        ["Instance"] = true, ["TweenService"] = true, ["UserInputService"] = true, ["RunService"] = true,
        ["HttpService"] = true,
    }
}
